EcruteakGym_Text_Intro:
	.string "Welcome to Ecruteak, a storied city.\n"
	.string "We have a tale that a legendary pokemon\l"
	.string "will come down to appear before a\p"
	.string "powerful trainer. I beleive that trainer\l"
	.string "will be me! Let me test myself against your  \p"
	.string "strength!$"

EcruteakGym_Text_Deafeated:
	.string "How are you so strong?$"

EcruteakGym_Text_Morty_postbattle:
	.string "Perhaps, I have more to learn\n"
	.string "before the rainbow pokemon will\n"
	.string "show itself to me. I thank you!$"

EcruteakGym_Text_NoRematch:
	.string "No problem, champ!.$"
EcruteakGym_Text_RematchQuestion:
	.string "Hey, champ! Want a rematch?$"
EcruteakGym_Text_RematchGo:
	.string "You got it champ!$"

EcruteakGym_Text_Morty_postrematch:
 .string "hi$"

EcruteakGym_Text_RebattleIntro:
 .string "Alright kid, time to\n"
 .string "really stretch our wings!$"
EcruteakGym_Text_RebattleDeafeated:
 .string "Oh man, I'm winded.\l"
 .string "Give this old bird a\p"
 .string "chance to roost!$"
