Lake_of_RageHouse2_TEXT_CYNDCOOLTRAINER::
    .string "Oh, hello.\n"
    .string "I found this CYNDAQUIL \p"
    .string "out by the lake.\n"
    .string "Would you be able to take care\p" 
    .string "of it?\n$"
Lake_of_RageHouse2_Text_ReceivedCyndaquil::
	.string "{PLAYER} received a Cyndaquil!$"
Lake_of_RageHouse2_Text_PlayerHasFullParty::
	.string "Ah, your party is full.$"
Lake_of_RageHouse2_TEXT_COOLTRAINER_THANKS::
	.string "Thanks for taking care\n" 
    .string "of that Cyndaquil!$"

