MohoganyGym_Text_Intro:
	.string "Pokemon have many experiences in\n"
	.string "their lives, just like we do.\l"
	.string "I, too, have seen and suffered\p"
	.string "much in my life. I have been training\l"
	.string "Pokemon since before you were born.\p"
	.string "I do not lose easily!$"

MohoganyGym_Text_Deafeated:
	.string "Hmm. Seems as if my luck has run out.$"

MohoganyGym_Text_Pryce_postbattle:
	.string "I am impressed by your prowess.\n"
	.string "With your strong will\n"
	.string "I know you will overcome\n"
	.string "all life's obstacles.$"

MohoganyGym_Text_NoRematch:
	.string "No problem, champ!.$"
MohoganyGym_Text_RematchQuestion:
	.string "Hey, champ! Want a rematch?$"
MohoganyGym_Text_RematchGo:
	.string "You got it champ!$"

MohoganyGym_Text_Pryce_postrematch:
    .string "hi$"

MohoganyGym_Text_RebattleIntro:
 .string "Alright kid, time to\n"
 .string "really stretch our wings!$"
MohoganyGym_Text_RebattleDeafeated:
 .string "Oh man, I'm winded.\l"
 .string "Give this old bird a\p"
 .string "chance to roost!$"
