FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Fwahahaha!\p"
    .string "A mere child like you dares to\n"
    .string "challenge me?\p"
    .string "The very idea makes me shiver\n"
    .string "with mirth!\p"
    .string "Very well, I shall show you true\n"
    .string "terror as a ninja master.\p"
    .string "Poison brings steady doom.\n"
    .string "Sleep renders foes helpless.\p"
    .string "Despair to the creeping horror of\n"
    .string "POISON-type POKéMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Humph!\n"
    .string "You have proven your worth!\p"
    .string "Here!\n"
    .string "Take the SOULBADGE!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "When afflicted by TOXIC, a POKéMON\n"
    .string "suffers more and more.\p"
    .string "It suffers worsening damage as the\n"
    .string "battle wears on!\p"
    .string "It will surely terrorize foes!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Now that you have the SOULBADGE,\n"
    .string "the DEFENSE of your POKéMON rises.\p"
    .string "It also lets you SURF outside of\n"
    .string "battle.\p"
    .string "Ah!\n"
    .string "Take this, too!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} received TM06\n"
    .string "from KOGA.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "Sealed within that TM06 lies\n"
    .string "TOXIC!\p"
    .string "It is a secret technique dating\n"
    .string "back some four hundred years.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Make space for this, child!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "Strength isn't the key for POKéMON.\n"
    .string "Do you understand this?\p"
    .string "POKéMON is about strategy!\p"
    .string "I'll show you how strategy can\n"
    .string "beat brute strength.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "What?\n"
    .string "Extraordinary!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "So, you mix brawn with brains?\n"
    .string "Good strategy!\p"
    .string "That's remarkable for a child\n"
    .string "TRAINER.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "I was a magician once upon a time.\p"
    .string "But I dreamt of becoming a ninja,\n"
    .string "so I joined this GYM.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "I'm done for!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Even though I've lost, I will keep\n"
    .string "training according to the teachings\l"
    .string "of KOGA, my ninja master.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Let's see you beat my special\n"
    .string "techniques!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "You had me fooled!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "I like poison and sleep techniques,\n"
    .string "as they linger after battle!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Stop right there!\p"
    .string "The famed invisible walls of\n"
    .string "FUCHSIA GYM have you frustrated?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Whoa!\n"
    .string "You've got it!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "You impressed me!\n"
    .string "Here's a hint!\p"
    .string "Look very closely for gaps in the\n"
    .string "invisible walls!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "I also study the way of the ninja\n"
    .string "with Master KOGA!\p"
    .string "Ninja have a long history of using\n"
    .string "animals!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Awoo!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "I still have much to learn.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Master KOGA comes from a long line\n"
    .string "of ninjas.\p"
    .string "What did you descend from?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "You're more skilled than I'd\n"
    .string "thought!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Where there is light, there is\n"
    .string "shadow!\p"
    .string "Light and shadow!\n"
    .string "Which do you choose?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "FUCHSIA GYM is a tricked-up place.\n"
    .string "It's riddled with invisible walls!\p"
    .string "KOGA might appear close, but he's\n"
    .string "blocked off.\p"
    .string "You have to find gaps in the walls\n"
    .string "to reach him.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "It's amazing how ninja can terrify,\n"
    .string "even now!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "FUCHSIA POKéMON GYM\n"
    .string "LEADER: KOGA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "FUCHSIA POKéMON GYM\n"
    .string "LEADER: KOGA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

FuchsiaCity_Gym_Text_RematchNotUnlocked:
    .string "Sorry, champ. You aren't \n"
    .string "ready for a rematch yet.\p"
    .string "Come on back after a while.$"

FuchsiaCity_Gym_Text_NoRematch:
	.string "No problem, champ.$"

FuchsiaCity_Gym_Text_RematchQuestion:
	.string "Hey, champ! Want a rematch?$"

FuchsiaCity_Gym_Text_RematchGo:
	.string "You got it champ!$"

FuchsiaCity_Gym_Text_Koga_postrematch:
 .string "With Trainers like you, the Pokémon\n"
 .string "League must be a place of formidable\p"
 .string "strength! Truly, it is something to be\p"
 .string "proud of! As it so happens, I have been\p"
 .string "thinking of aiming to join the Elite\p"
 .string "Four myself...$"

FuchsiaCity_Gym_Text_RebattleIntro:
 .string "Fwahahaha! If it isn't the child. It\n"
 .string "seems we are fated to meet once again.\p"
 .string "You have come at a truly opportune\p"
 .string "time. I was just thinking that I wanted\p"
 .string "to test my newly refined sinister\p"
 .string "techniques... in a battle that will not\p"
 .string "only defeat you, but will also\p"
 .string "demonstrate my fatherly dignity to my\p"
 .string "daughter!$"

FuchsiaCity_Gym_Text_RebattleDeafeated:
 .string "If I am not strong enough to defeat\n"
 .string "you now, there is but one thing to do.\p"
 .string "I must hone my skills.$"
