BlackthornGym_Text_Intro:
	.string "I am Clair. The world's best\n"
	.string "dragon master. I was trained by\l"
	.string "my cousin Lance of the Elite Four\p"
	.string "Do you still want to take me on?\l"
	.string "As a trainer, I will use my full\p"
	.string "power against any opponent!$"

BlackthornGym_Text_Deafeated:
	.string "I lost? I don't believe it.$"

BlackthornGym_Text_Clair_postbattle:
	.string "What?! Come to brag about\n"
	.string "your victory? Fine. I'll say \n"
	.string "it to you. Congratulations!\n"
	.string "You were really tough! There!\n"
	.string "Are you happy now?$"
BlackthornGym_Text_NoRematch:
	.string "No problem, champ!.$"
BlackthornGym_Text_RematchQuestion:
	.string "Hey, champ! Want a rematch?$"
BlackthornGym_Text_RematchGo:
	.string "You got it champ!$"

BlackthornGym_Text_Clair_postrematch:
 .string "hi$"

BlackthornGym_Text_RebattleIntro:
 .string "Alright kid, time to\n"
 .string "really stretch our wings!$"
BlackthornGym_Text_RebattleDeafeated:
 .string "Oh man, I'm winded.\l"
 .string "Give this old bird a\p"
 .string "chance to roost!$"
