Cianwood_House1_TEXT_TOTOBLACKBELT::
    .string "You there! Can you raise this\n"
    .string "TOTODILE? It deserves to\p"
    .string "adventure, but I am bound to my\n" 
    .string "training.\n$"
Cianwood_House1_Text_ReceivedTotodile::
	.string "{PLAYER} received a Totodile!$"
Cianwood_House1_Text_PlayerHasFullParty::
	.string "Ah, your party is full.$"
Cianwood_House1_TEXT_BLACKBELT_THANKS::
	.string "Thanks for taking care\n" 
    .string "of that Totodile!$"

