Text_Ecruteak_DanceTheater_MysticTicketGive:
	.string "The Legends foretold your\n"
	.string "arrival.$"

Text_Ecruteak_DanceTheater_GivingMysticTicket:
	.string "Take this!$"

Text_Ecruteak_DanceTheater_HasMysticTicketAlready:
	.string "The spirits have spoken\n"
	.string "The Legends shall return!$"

Text_Ecruteak_DanceTheater_MysticBagIsFull:
	.string "It seems you lack space.$"
Text_Ecruteak_DanceTheater_Defeat_Morty:
 .string "Greeting's Trainer. Our city\n"
 .string "has a legend about a trainer\p"
 .string "who will return our legendary\p"
 .string "birds, HO-OH, and LUGIA from\p"
 .string "hiding. A trainer who has defeated\p"
 .string "the Leader of this city may\p"
 .string "just be the one.$"
