OlivineGym_Text_Intro:
	.string "Oh...um, hello, my name is Jasmine,\n"
	.string "and I like the strong and tough STEEL type\l"
	.string "pokemon. \p"
	.string "So... Um...perhaps we could be friends\l"
	.string "after this? Anyway let's\p"
	.string "battle!$"

OlivineGym_Text_Deafeated:
	.string "Well done...$"

OlivineGym_Text_Jasmine_postbattle:
	.string "You are a better battler than me.\n"
	.string "Um... I don't know how to say this,\n"
	.string "but good luck... $"

OlivineGym_Text_NoRematch:
	.string "No problem, champ!.$"
OlivineGym_Text_RematchQuestion:
	.string "Hey, champ! Want a rematch?$"
OlivineGym_Text_RematchGo:
	.string "You got it champ!$"

OlivineGym_Text_Jasmine_postrematch:
 .string "hi$"

OlivineGym_Text_RebattleIntro:
 .string "Alright kid, time to\n"
 .string "really stretch our wings!$"
OlivineGym_Text_RebattleDeafeated:
 .string "Oh man, I'm winded.\l"
 .string "Give this old bird a\p"
 .string "chance to roost!$"
