CeruleanCity_Gym_Text_MistyIntro::
    .string "Hi, you're a new face!\p"
    .string "Only those TRAINERS who have a\n"
    .string "policy about POKéMON can turn pro.\p"
    .string "What is your approach when you\n"
    .string "catch and train POKéMON?\p"
    .string "My policy is an all-out offensive\n"
    .string "with WATER-type POKéMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 teaches WATER PULSE.\p"
    .string "Use it on an aquatic POKéMON!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "The CASCADEBADGE makes all\n"
    .string "POKéMON up to Lv. 30 obey.\p"
    .string "That includes even outsiders you\n"
    .string "got in trades.\p"
    .string "There's more. You can now use CUT\n"
    .string "anytime, even out of battle.\p"
    .string "You can CUT down small trees to\n"
    .string "open new pathways.\p"
    .string "You can also have my favorite TM.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} received TM03\n"
    .string "from MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "You better make room for this!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Wow!\n"
    .string "You're too much!\p"
    .string "All right!\p"
    .string "You can have the CASCADEBADGE to\n"
    .string "show you beat me.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "What? You?\n"
    .string "I'm more than good enough for you!\p"
    .string "MISTY won't have to be bothered.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "You overwhelmed me!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "You have to face other TRAINERS\n"
    .string "to see how good you really are.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Splash!\p"
    .string "I'm first up!\n"
    .string "Let's do it!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "That can't be!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY is a TRAINER who's going to\n"
    .string "keep improving.\p"
    .string "She won't lose to someone like you!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Let me give you some advice!\p"
    .string "The LEADER, MISTY, is a pro who\n"
    .string "uses WATER-type POKéMON.\p"
    .string "You can drain all their water with\n"
    .string "GRASS-type POKéMON.\p"
    .string "Or, you might use ELECTRIC-type\n"
    .string "POKéMON and zap them!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "You beat MISTY!\n"
    .string "See, what'd I tell ya?\p"
    .string "You and me, kid, we make a pretty\n"
    .string "darn-good team!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

CeruleanCity_Gym_Text_RematchNotUnlocked:
    .string "Sorry, champ. You aren't \n"
    .string "ready for a rematch yet.\p"
    .string "Come on back after a while.$"

CeruleanCity_Gym_Text_NoRematch:
	.string "No problem, champ.$"

CeruleanCity_Gym_Text_RematchQuestion:
	.string "Hey, champ! Want a rematch?$"

CeruleanCity_Gym_Text_RematchGo:
	.string "You got it champ!$"

CeruleanCity_Gym_Text_Misty_postrematch:
 .string "I lost... I need to try swimming around\n"
 .string "for a bit so that I can clear my head of\p"
 .string "these feelings. ...I definitely won't\p"
 .string "lose next time!$"
 

CeruleanCity_Gym_Text_RebattleIntro:
 .string "I heard an interesting rumor! Not only\n" 
 .string "did you and that other kid defeat \p"
 .string "those Team Rocket guys, but you also\p"
 .string "met again in the battle for Champion.\p"
 .string "Argh! I just can't take it anymore!\p"
 .string "You've gotten so strong that I just\p"
 .string "absolutely have to battle you again!\p"
 .string "You got that? No refusing!$"
 
CeruleanCity_Gym_Text_RebattleDeafeated:
 .string "Hmph! How annoying!$"
