Olivine_House2_TEXT_CHIKBALDMAN::
    .string "Hey there!.\n"
    .string "I found this CHIKORITA \p"
    .string "by the lighthouse.\n"
    .string "Would you mind taking it\p" 
    .string "off my hands?\n$"
Olivine_House2_Text_ReceivedChikorita::
	.string "{PLAYER} received a Chikorita!$"
Olivine_House2_Text_PlayerHasFullParty::
	.string "Ah, your party is full.$"
Olivine_House2_TEXT_BALDMAN_THANKS::
	.string "Thanks for taking care\n" 
    .string "of that Chikorita!$"
