CianwoodGym_Text_Intro:
	.string "WAHAHAH! So you've come this far!\n"
	.string "Let me tell you, I'm tough!\l"
	.string "My Pokemon will crush stones\p"
	.string "and shatter bones! \l"
	.string "Come on. We shall do battle!$"

CianwoodGym_Text_Deafeated:
	.string "We...lost...$"

CianwoodGym_Text_Chuck_postbattle:
	.string "Hmm... I lost? How about that!\n"
	.string "All right. Wahahah!\n"
	.string "I enjoyed battling you!$"

CianwoodGym_Text_NoRematch:
	.string "No problem, champ!.$"
CianwoodGym_Text_RematchQuestion:
	.string "Hey, champ! Want a rematch?$"
CianwoodGym_Text_RematchGo:
	.string "You got it champ!$"

CianwoodGym_Text_Chuck_postrematch:
 .string "hi$"

CianwoodGym_Text_RebattleIntro:
 .string "Alright kid, time to\n"
 .string "really stretch our wings!$"
CianwoodGym_Text_RebattleDeafeated:
 .string "Oh man, I'm winded.\l"
 .string "Give this old bird a\p"
 .string "chance to roost!$"
