
#ifndef GUARD_BATTLE_TRANSITION_H
#define GUARD_BATTLE_TRANSITION_H

#include "global.h"

enum
{
    MUGSHOT_COLOR_PINK,
    MUGSHOT_COLOR_YELLOW,
    MUGSHOT_COLOR_BLUE,
    MUGSHOT_COLOR_PURPLE,
    MUGSHOT_COLOR_GREEN,
    MUGSHOT_COLOR_STARS,
    MUGSHOT_COLOR_DARK_RED,
    MUGSHOT_COLOR_RED_ORANGE,
    MUGSHOT_COLOR_RED_BLACK,
    MUGSHOT_COLOR_BROWN_GREY,
    MUGSHOT_COLOR_LIGHT_BLUE,
    MUGSHOT_COLOR_YELLOW_GREEN,
    MUGSHOT_COLOR_LAVENDER_PURPLES,
    MUGSHOT_COLOR_GREEN_GREEN,
    MUGSHOT_COLOR_DARK_PURPLES,
    MUGSHOT_COLOR_PINK_WHITE,
    MUGSHOT_COLOR_SKY_BLUE_GREY,
    MUGSHOT_COLOR_BLUE_YELLOW_RED_GREEN,
    MUGSHOT_COLOR_DARK_BLUE_AQUA,
    MUGSHOT_COLOR_DARK_BLUE_GREY,
    MUGSHOT_COLOR_DARK_PURPLE_GREEN,
    MUGSHOT_COLOR_EARTH_BROWN_GREY,
    MUGSHOT_COLOR_GREEN_BROWN,
    MUGSHOT_COLOR_LIGHT_BLUE_WHITE,
    MUGSHOT_COLOR_PURPLE_BLACK,
    MUGSHOT_COLOR_RED_YELLOW,
    MUGSHOT_COLOR_SILVER_YELLOW,
    MUGSHOT_COLOR_GRASS,
    MUGSHOT_COLOR_WATER,
    MUGSHOT_COLOR_FIRE,
    MUGSHOT_COLOR_COUNT
};


enum {
    B_TRANSITION_BLUR,
    B_TRANSITION_SWIRL,
    B_TRANSITION_SHUFFLE,
    B_TRANSITION_BIG_POKEBALL,
    B_TRANSITION_POKEBALLS_TRAIL,
    B_TRANSITION_CLOCKWISE_WIPE,
    B_TRANSITION_RIPPLE,
    B_TRANSITION_WAVE,
    B_TRANSITION_SLICE, 
    B_TRANSITION_WHITE_BARS_FADE,
    B_TRANSITION_GRID_SQUARES,
    B_TRANSITION_ANGLED_WIPES,
    B_TRANSITION_MUGSHOT,
    B_TRANSITION_SPIRAL,
    B_TRANSITION_COUNT
};

extern const struct SpritePalette gSpritePalette_Pokeball;

bool8 IsBattleTransitionDone(void);
void BattleTransition_StartOnField(u8 transitionId);
bool8 FldEff_PokeballTrail(void);

#endif // GUARD_BATTLE_TRANSITION_H