PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "POKéMON TOWER was erected in the\n"
    .string "memory of POKéMON that died.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Did you come to pay respects?\p"
    .string "Bless your POKéMON-loving heart,\n"
    .string "son.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Did you come to pay respects?\p"
    .string "Bless your POKéMON-loving heart,\n"
    .string "girl.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "I came to pray for my dearly\n"
    .string "departed CLEFAIRY.\p"
    .string "Sniff!\n"
    .string "I'm awash in tears…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "My GROWLITHE…\n"
    .string "Why did you die?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "I am a CHANNELER.\p"
    .string "There are spirits up to mischief.\n"
    .string "I sense them high in the TOWER.$"


LavenderTower_TEXT_BULBOLDWOMAN::
    .string "Oh, hello.\n"
    .string "This BULBASAUR lost it's\p"
    .string "mother.\n"
    .string "Would you be able to take care\p" 
    .string "of it? I'm afraid I'm too old.\n$"
LavenderTower_Text_ReceivedBulbasaur::
	.string "{PLAYER} received a Bulbasaur!$"
LavenderTower_Text_PlayerHasFullParty::
	.string "Ah, your party is full.$"
LavenderTower_TEXT_OLDWOMAN_THANKS::
	.string "Thanks for taking care\n" 
    .string "of that Bulbasaur!$"
