GoldenrodGym_Text_Intro:
	.string "Oh, hello, are you the tough trainer\n"
	.string "I was told about? Well I don't plan\l"
	.string "on losing so don't get your hopes up.\p"
	.string "I haven't been doing this too long but I'm \l"
	.string "already good enough to be a GYM LEADER.\p"
	.string "My cute and tough pokemon will take you down!$"

GoldenrodGym_Text_Deafeated:
	.string "That's not fair!$"

GoldenrodGym_Text_Whitney_postbattle:
	.string "You're a meanie.\n"
	.string "Good luck with the others.\n"
	.string "My poor cute pokemon.$"

GoldenrodGym_Text_NoRematch:
	.string "No problem, champ!.$"
GoldenrodGym_Text_RematchQuestion:
	.string "Hey, champ! Want a rematch?$"
GoldenrodGym_Text_RematchGo:
	.string "You got it champ!$"

GoldenrodGym_Text_Whitney_postrematch:
 .string "hi$"

GoldenrodGym_Text_RebattleIntro:
 .string "Alright kid, time to\n"
 .string "really stretch our wings!$"
GoldenrodGym_Text_RebattleDeafeated:
 .string "Oh man, I'm winded.\l"
 .string "Give this old bird a\p"
 .string "chance to roost!$"
