VioletGym_Text_NoRematch:
	.string "No problem, champ!.$"
VioletGym_Text_RematchQuestion:
	.string "Hey, champ! Want a rematch?$"
VioletGym_Text_RematchGo:
	.string "You got it champ!$"
VioletGym_Text_Intro:
	.string "What's up high flyer? Got word from\n"
	.string "Bruno that a hot shot was soaring\l"
	.string "through the strongest trainers.\p"
	.string "Gotta warn you though, Johto's GYM\l"
	.string "LEADERS won't hold back on you. Let's\p"
	.string "fly!$"
VioletGym_Text_Deafeated:
	.string "Now that was a battle!$"
VioletGym_Text_Walker_postbattle:
 .string "Kid, I think you've got what\n"
 .string "it takes to jet straight to\l"
 .string "the top!\p"



VioletGym_Text_Walker_postrematch:
 .string "hi$"

VioletGym_Text_RebattleIntro:
 .string "Alright kid, time to\n"
 .string "really stretch our wings!$"
VioletGym_Text_RebattleDeafeated:
 .string "Oh man, I'm winded.\l"
 .string "Give this old bird a\p"
 .string "chance to roost!$"
