name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      GAME_REVISION: 0
      MODERN: 0
      COMPARE: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev

      - name: Set Up AGBCC
        run: |
          git clone https://github.com/pret/agbcc agbcc
          cd agbcc
          ./build.sh
          ./install.sh ../

      - name: Verify Directory and Makefile
        run: |
          pwd
          ls -la

      - name: Build Project
        run: make -j$(nproc)
