name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      GAME_REVISION: 0
      MODERN: 0
      COMPARE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev

      - name: Debug - List Directory Contents
        run: ls -R
        working-directory: .

      - name: Build Project
        run: make -j${nproc}
        working-directory: ./FireRedRemastered  # Adjust this path if needed based on the directory structure

      - name: Move symfiles
        if: ${{ github.event_name == 'push' }}
        run: |
          mkdir -p symbols
          cp ./*.sym symbols/
          echo "SYMBOLS_COMMIT_MSG=$( git log --format=%s ${GITHUB_SHA} )" >> $GITHUB_ENV
