AzaleaGym_Text_Intro:
	.string "Hey there! Did you know that bug\n"
	.string "pokemon tend to be strong early but \l"
	.string "don't tend to be as strong later on.\p"
	.string "Doesn't bother me though, I just think\p"
	.string "they are neat. Ok, let's battle!$"

AzaleaGym_Text_Deafeated:
	.string "Fascinating!$"

AzaleaGym_Text_Bugsy_postbattle:
	.string "That was quite the battle. \n"
	.string "Here's a tip from a local,\n"
	.string "the Ilex Forrest is home \n"
	.string "to a many intresting pokemon!$"

AzaleaGym_Text_NoRematch:
	.string "No problem, champ!.$"
AzaleaGym_Text_RematchQuestion:
	.string "Hey, champ! Want a rematch?$"
AzaleaGym_Text_RematchGo:
	.string "You got it champ!$"

AzaleaGym_Text_Bugsy_postrematch:
 .string "hi$"

AzaleaGym_Text_RebattleIntro:
 .string "Alright kid, time to\n"
 .string "really stretch our wings!$"
AzaleaGym_Text_RebattleDeafeated:
 .string "Oh man, I'm winded.\l"
 .string "Give this old bird a\p"
 .string "chance to roost!$"
